# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: myfamily

before:
  hooks:
    - go mod tidy

builds:
  - id: myfamily
    main: ./cmd/myfamily
    binary: myfamily
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

changelog:
  # release-please handles changelog, so skip goreleaser's
  disable: true

release:
  github:
    owner: cacack
    name: my-family
  # Append to existing release created by release-please
  mode: append
