# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  status:
    # Project coverage - overall repository coverage
    project:
      default:
        # Allow coverage to drop by up to 1% before failing
        # This prevents false failures on dependency updates
        threshold: 1%
        # Only check coverage on code that can be tested
        paths:
          - "internal/"
        # Exclude paths that don't need coverage
        removed_code_behavior: adjust_base

    # Patch coverage - coverage of changed lines in PR
    patch:
      default:
        # Require 80% of new lines to be covered
        target: 80%
        # Only apply to actual code changes
        paths:
          - "internal/"

# Ignore files that don't need test coverage
ignore:
  - "cmd/**/*"
  - "web/**/*"
  - "**/*_test.go"
  - "**/testdata/**"
  - "internal/repository/postgres/**"  # Requires live DB
  - "internal/repository/sqlite/**"    # Integration tests cover this

# Comment configuration for PRs
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
