# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference
#
# Aligned with local checks:
# - Local: 85% per-package, 75% total (make check-coverage)
# - Codecov: Same targets, informational only

coverage:
  status:
    # Project coverage - overall repository coverage
    project:
      default:
        # Target 85% to match local per-package threshold
        target: 85%
        # Allow 2% drop to accommodate new features with complex setup
        threshold: 2%
        # Only check coverage on code that can be tested
        paths:
          - "internal/"
        # Exclude paths that don't need coverage
        removed_code_behavior: adjust_base
        # Don't block PRs - informational only
        informational: true

    # Patch coverage - coverage of changed lines in PR
    patch:
      default:
        # Target 75% of new lines - prioritize meaningful tests over line count
        target: 75%
        # Only apply to actual code changes
        paths:
          - "internal/"
        # Don't block PRs - informational only
        informational: true

# Ignore files that don't need test coverage
ignore:
  - "cmd/**/*"
  - "web/**/*"
  - "**/*_test.go"
  - "**/testdata/**"
  - "internal/repository/postgres/**"  # Requires live DB
  - "internal/repository/sqlite/**"    # Integration tests cover this

# Comment configuration for PRs
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
