package citation

import "github.com/cacack/my-family/internal/domain"

// allTemplates defines the Evidence Explained citation templates.
// Template IDs are stable and must never be renamed once released.
//
// Format strings use Go text/template syntax. The context object has:
//   - Source fields: .Author, .Title, .Publisher, .PublishDate, .URL,
//     .RepositoryName, .CollectionName, .CallNumber
//   - Citation fields: .Page, .Volume
//   - Template fields: accessed via .Field "key"
//
// Custom functions available: italic, comma, period, paren, quoted.
var allTemplates = []Template{
	// ── Census Records ──────────────────────────────────────────────

	{
		ID:          "census.us.federal",
		Name:        "U.S. Federal Census",
		Category:    "Census Records",
		Description: "U.S. federal population census schedules (1790-1950).",
		SourceTypes: []domain.SourceType{domain.SourceCensus},
		Fields: []FieldDef{
			{Key: "year", Label: "Census Year", HelpText: "Year the census was taken (e.g. 1850)", Required: true},
			{Key: "state", Label: "State", HelpText: "State or territory", Required: true},
			{Key: "county", Label: "County", HelpText: "County name", Required: true},
			{Key: "town", Label: "Town/Township", HelpText: "City, town, or township"},
			{Key: "enum_district", Label: "Enumeration District", HelpText: "E.D. number"},
			{Key: "sheet", Label: "Sheet/Page", HelpText: "Sheet or page number"},
			{Key: "line", Label: "Line Number", HelpText: "Line number on the page"},
			{Key: "dwelling", Label: "Dwelling Number", HelpText: "Dwelling number"},
			{Key: "family_num", Label: "Family Number", HelpText: "Family number"},
			{Key: "person_name", Label: "Person Cited", HelpText: "Name as it appears in the record", Required: true},
			{Key: "nara_pub", Label: "NARA Publication", HelpText: "NARA microfilm publication number (e.g. T624)"},
			{Key: "nara_roll", Label: "NARA Roll", HelpText: "Microfilm roll number"},
		},
		FullFormat:  `{{.Field "year"}} U.S. Census, {{.Field "state"}}, {{.Field "county"}} County{{with .Field "town"}}, {{.}}{{end}}{{with .Field "enum_district"}}, enumeration district {{.}}{{end}}{{with .Field "sheet"}}, sheet {{.}}{{end}}{{with .Field "line"}}, line {{.}}{{end}}; {{.Field "person_name"}} household{{with .Field "nara_pub"}}; NARA microfilm publication {{.}}{{end}}{{with .Field "nara_roll"}}, roll {{.}}{{end}}.`,
		ShortFormat: `{{.Field "year"}} U.S. Census, {{.Field "county"}} Co., {{.Field "state"}}{{with .Field "sheet"}}, sheet {{.}}{{end}}, {{.Field "person_name"}}.`,
	},
	{
		ID:          "census.state",
		Name:        "State/Territorial Census",
		Category:    "Census Records",
		Description: "State or territorial census schedules.",
		SourceTypes: []domain.SourceType{domain.SourceCensus},
		Fields: []FieldDef{
			{Key: "year", Label: "Census Year", Required: true},
			{Key: "state", Label: "State/Territory", Required: true},
			{Key: "county", Label: "County", Required: true},
			{Key: "town", Label: "Town/Township"},
			{Key: "page", Label: "Page/Sheet"},
			{Key: "line", Label: "Line Number"},
			{Key: "person_name", Label: "Person Cited", Required: true},
			{Key: "repository", Label: "Repository", HelpText: "Archive or library holding the record"},
		},
		FullFormat:  `{{.Field "year"}} {{.Field "state"}} State Census, {{.Field "county"}} County{{with .Field "town"}}, {{.}}{{end}}{{with .Field "page"}}, p. {{.}}{{end}}{{with .Field "line"}}, line {{.}}{{end}}; {{.Field "person_name"}}{{with .Field "repository"}}; {{.}}{{end}}.`,
		ShortFormat: `{{.Field "year"}} {{.Field "state"}} Census, {{.Field "county"}} Co.{{with .Field "page"}}, p. {{.}}{{end}}, {{.Field "person_name"}}.`,
	},
	{
		ID:          "census.non_us",
		Name:        "Non-U.S. Census",
		Category:    "Census Records",
		Description: "Census records from countries outside the United States.",
		SourceTypes: []domain.SourceType{domain.SourceCensus},
		Fields: []FieldDef{
			{Key: "year", Label: "Census Year", Required: true},
			{Key: "country", Label: "Country", Required: true},
			{Key: "jurisdiction", Label: "Jurisdiction", HelpText: "Province, county, district, etc.", Required: true},
			{Key: "locality", Label: "Locality", HelpText: "Town, parish, or village"},
			{Key: "piece", Label: "Piece/Folio", HelpText: "Reference number or folio"},
			{Key: "person_name", Label: "Person Cited", Required: true},
			{Key: "archive", Label: "Archive", HelpText: "National archive or repository"},
		},
		FullFormat:  `{{.Field "year"}} Census, {{.Field "country"}}, {{.Field "jurisdiction"}}{{with .Field "locality"}}, {{.}}{{end}}{{with .Field "piece"}}, piece/folio {{.}}{{end}}; {{.Field "person_name"}}{{with .Field "archive"}}; {{.}}{{end}}.`,
		ShortFormat: `{{.Field "year"}} Census, {{.Field "jurisdiction"}}, {{.Field "country"}}{{with .Field "piece"}}, {{.}}{{end}}, {{.Field "person_name"}}.`,
	},

	// ── Vital Records ───────────────────────────────────────────────

	{
		ID:          "vital.birth",
		Name:        "Birth Certificate/Record",
		Category:    "Vital Records",
		Description: "Official birth certificates or registrations.",
		SourceTypes: []domain.SourceType{domain.SourceVitalRecord},
		Fields: []FieldDef{
			{Key: "jurisdiction", Label: "Jurisdiction", HelpText: "State, county, or country", Required: true},
			{Key: "record_type", Label: "Record Type", HelpText: "e.g. Certificate of Birth, Birth Register"},
			{Key: "registrant", Label: "Registrant Name", HelpText: "Name as it appears on the record", Required: true},
			{Key: "date", Label: "Event Date", HelpText: "Date of birth"},
			{Key: "certificate_num", Label: "Certificate Number"},
			{Key: "registrar_office", Label: "Registrar/Office", HelpText: "Issuing office or registrar"},
		},
		FullFormat:  `{{.Field "jurisdiction"}}{{with .Field "record_type"}}, {{.}}{{end}}, {{.Field "registrant"}}{{with .Field "date"}}, {{.}}{{end}}{{with .Field "certificate_num"}}; certificate no. {{.}}{{end}}{{with .Field "registrar_office"}}; {{.}}{{end}}.`,
		ShortFormat: `{{.Field "jurisdiction"}}, birth record, {{.Field "registrant"}}{{with .Field "date"}} ({{.}}){{end}}.`,
	},
	{
		ID:          "vital.death",
		Name:        "Death Certificate/Record",
		Category:    "Vital Records",
		Description: "Official death certificates or registrations.",
		SourceTypes: []domain.SourceType{domain.SourceVitalRecord},
		Fields: []FieldDef{
			{Key: "jurisdiction", Label: "Jurisdiction", HelpText: "State, county, or country", Required: true},
			{Key: "record_type", Label: "Record Type", HelpText: "e.g. Certificate of Death, Death Register"},
			{Key: "decedent", Label: "Decedent Name", Required: true},
			{Key: "date", Label: "Event Date", HelpText: "Date of death"},
			{Key: "certificate_num", Label: "Certificate Number"},
			{Key: "registrar_office", Label: "Registrar/Office"},
			{Key: "file_num", Label: "File Number"},
		},
		FullFormat:  `{{.Field "jurisdiction"}}{{with .Field "record_type"}}, {{.}}{{end}}, {{.Field "decedent"}}{{with .Field "date"}}, {{.}}{{end}}{{with .Field "certificate_num"}}; certificate no. {{.}}{{end}}{{with .Field "file_num"}}; file no. {{.}}{{end}}{{with .Field "registrar_office"}}; {{.}}{{end}}.`,
		ShortFormat: `{{.Field "jurisdiction"}}, death record, {{.Field "decedent"}}{{with .Field "date"}} ({{.}}){{end}}.`,
	},
	{
		ID:          "vital.marriage",
		Name:        "Marriage Certificate/Record",
		Category:    "Vital Records",
		Description: "Official marriage certificates, licenses, or registrations.",
		SourceTypes: []domain.SourceType{domain.SourceVitalRecord},
		Fields: []FieldDef{
			{Key: "jurisdiction", Label: "Jurisdiction", Required: true},
			{Key: "record_type", Label: "Record Type", HelpText: "e.g. Marriage License, Marriage Certificate"},
			{Key: "groom", Label: "Groom Name", Required: true},
			{Key: "bride", Label: "Bride Name", Required: true},
			{Key: "date", Label: "Event Date"},
			{Key: "certificate_num", Label: "Certificate/License Number"},
			{Key: "book_page", Label: "Book/Page", HelpText: "Record book and page number"},
			{Key: "registrar_office", Label: "Registrar/Office"},
		},
		FullFormat:  `{{.Field "jurisdiction"}}{{with .Field "record_type"}}, {{.}}{{end}}, {{.Field "groom"}} and {{.Field "bride"}}{{with .Field "date"}}, {{.}}{{end}}{{with .Field "certificate_num"}}; no. {{.}}{{end}}{{with .Field "book_page"}}; {{.}}{{end}}{{with .Field "registrar_office"}}; {{.}}{{end}}.`,
		ShortFormat: `{{.Field "jurisdiction"}}, marriage record, {{.Field "groom"}} and {{.Field "bride"}}{{with .Field "date"}} ({{.}}){{end}}.`,
	},
	{
		ID:          "vital.civil_registration",
		Name:        "Civil Registration (Non-U.S.)",
		Category:    "Vital Records",
		Description: "Civil registration records from countries outside the U.S.",
		SourceTypes: []domain.SourceType{domain.SourceVitalRecord},
		Fields: []FieldDef{
			{Key: "country", Label: "Country", Required: true},
			{Key: "jurisdiction", Label: "Jurisdiction", HelpText: "Province, district, or municipality", Required: true},
			{Key: "record_type", Label: "Record Type", HelpText: "e.g. Birth, Marriage, Death", Required: true},
			{Key: "registrant", Label: "Registrant/Subject Name", Required: true},
			{Key: "date", Label: "Event Date"},
			{Key: "register_num", Label: "Register/Entry Number"},
			{Key: "archive", Label: "Archive"},
		},
		FullFormat:  `{{.Field "country"}}, {{.Field "jurisdiction"}}, {{.Field "record_type"}}, {{.Field "registrant"}}{{with .Field "date"}}, {{.}}{{end}}{{with .Field "register_num"}}; entry no. {{.}}{{end}}{{with .Field "archive"}}; {{.}}{{end}}.`,
		ShortFormat: `{{.Field "jurisdiction"}}, {{.Field "country"}}, {{.Field "record_type"}}, {{.Field "registrant"}}{{with .Field "date"}} ({{.}}){{end}}.`,
	},

	// ── Church Records ──────────────────────────────────────────────

	{
		ID:          "church.baptism",
		Name:        "Baptism/Christening Record",
		Category:    "Church Records",
		Description: "Church baptism or christening register entries.",
		SourceTypes: []domain.SourceType{domain.SourceChurch},
		Fields: []FieldDef{
			{Key: "church", Label: "Church Name", Required: true},
			{Key: "location", Label: "Location", HelpText: "City, county, state/country", Required: true},
			{Key: "denomination", Label: "Denomination"},
			{Key: "person_name", Label: "Person Baptized", Required: true},
			{Key: "date", Label: "Date of Baptism"},
			{Key: "parents", Label: "Parents Named"},
			{Key: "register", Label: "Register/Volume"},
			{Key: "page", Label: "Page"},
		},
		FullFormat:  `{{.Field "church"}}, {{.Field "location"}}{{with .Field "denomination"}} ({{.}}){{end}}, baptism record for {{.Field "person_name"}}{{with .Field "date"}}, {{.}}{{end}}{{with .Field "parents"}}; parents: {{.}}{{end}}{{with .Field "register"}}; {{.}}{{end}}{{with .Field "page"}}, p. {{.}}{{end}}.`,
		ShortFormat: `{{.Field "church"}}, {{.Field "location"}}, baptism of {{.Field "person_name"}}{{with .Field "date"}} ({{.}}){{end}}.`,
	},
	{
		ID:          "church.marriage",
		Name:        "Church Marriage Record",
		Category:    "Church Records",
		Description: "Church marriage register entries.",
		SourceTypes: []domain.SourceType{domain.SourceChurch},
		Fields: []FieldDef{
			{Key: "church", Label: "Church Name", Required: true},
			{Key: "location", Label: "Location", Required: true},
			{Key: "denomination", Label: "Denomination"},
			{Key: "groom", Label: "Groom Name", Required: true},
			{Key: "bride", Label: "Bride Name", Required: true},
			{Key: "date", Label: "Date of Marriage"},
			{Key: "register", Label: "Register/Volume"},
			{Key: "page", Label: "Page"},
		},
		FullFormat:  `{{.Field "church"}}, {{.Field "location"}}{{with .Field "denomination"}} ({{.}}){{end}}, marriage of {{.Field "groom"}} and {{.Field "bride"}}{{with .Field "date"}}, {{.}}{{end}}{{with .Field "register"}}; {{.}}{{end}}{{with .Field "page"}}, p. {{.}}{{end}}.`,
		ShortFormat: `{{.Field "church"}}, {{.Field "location"}}, marriage of {{.Field "groom"}} and {{.Field "bride"}}{{with .Field "date"}} ({{.}}){{end}}.`,
	},
	{
		ID:          "church.burial",
		Name:        "Church Burial Record",
		Category:    "Church Records",
		Description: "Church burial or funeral register entries.",
		SourceTypes: []domain.SourceType{domain.SourceChurch},
		Fields: []FieldDef{
			{Key: "church", Label: "Church Name", Required: true},
			{Key: "location", Label: "Location", Required: true},
			{Key: "denomination", Label: "Denomination"},
			{Key: "decedent", Label: "Decedent Name", Required: true},
			{Key: "date", Label: "Date of Burial"},
			{Key: "register", Label: "Register/Volume"},
			{Key: "page", Label: "Page"},
		},
		FullFormat:  `{{.Field "church"}}, {{.Field "location"}}{{with .Field "denomination"}} ({{.}}){{end}}, burial record for {{.Field "decedent"}}{{with .Field "date"}}, {{.}}{{end}}{{with .Field "register"}}; {{.}}{{end}}{{with .Field "page"}}, p. {{.}}{{end}}.`,
		ShortFormat: `{{.Field "church"}}, {{.Field "location"}}, burial of {{.Field "decedent"}}{{with .Field "date"}} ({{.}}){{end}}.`,
	},

	// ── Newspapers ──────────────────────────────────────────────────

	{
		ID:          "newspaper.article_byline",
		Name:        "Newspaper Article (with Byline)",
		Category:    "Newspapers",
		Description: "Newspaper article with a named author.",
		SourceTypes: []domain.SourceType{domain.SourceNewspaper},
		Fields: []FieldDef{
			{Key: "author", Label: "Author", Required: true},
			{Key: "article_title", Label: "Article Title", Required: true},
			{Key: "newspaper", Label: "Newspaper Name", Required: true},
			{Key: "location", Label: "Place of Publication"},
			{Key: "date", Label: "Publication Date", Required: true},
			{Key: "page", Label: "Page"},
			{Key: "column", Label: "Column"},
		},
		FullFormat:  `{{.Field "author"}}, "{{.Field "article_title"}}," {{.Field "newspaper"}}{{with .Field "location"}} ({{.}}){{end}}, {{.Field "date"}}{{with .Field "page"}}, p. {{.}}{{end}}{{with .Field "column"}}, col. {{.}}{{end}}.`,
		ShortFormat: `{{.Field "author"}}, "{{.Field "article_title"}}," {{.Field "newspaper"}}, {{.Field "date"}}.`,
	},
	{
		ID:          "newspaper.article_no_byline",
		Name:        "Newspaper Article (no Byline)",
		Category:    "Newspapers",
		Description: "Newspaper article without a named author.",
		SourceTypes: []domain.SourceType{domain.SourceNewspaper},
		Fields: []FieldDef{
			{Key: "article_title", Label: "Article Title", Required: true},
			{Key: "newspaper", Label: "Newspaper Name", Required: true},
			{Key: "location", Label: "Place of Publication"},
			{Key: "date", Label: "Publication Date", Required: true},
			{Key: "page", Label: "Page"},
			{Key: "column", Label: "Column"},
		},
		FullFormat:  `"{{.Field "article_title"}}," {{.Field "newspaper"}}{{with .Field "location"}} ({{.}}){{end}}, {{.Field "date"}}{{with .Field "page"}}, p. {{.}}{{end}}{{with .Field "column"}}, col. {{.}}{{end}}.`,
		ShortFormat: `"{{.Field "article_title"}}," {{.Field "newspaper"}}, {{.Field "date"}}.`,
	},
	{
		ID:          "newspaper.obituary",
		Name:        "Obituary",
		Category:    "Newspapers",
		Description: "Published obituary or death notice.",
		SourceTypes: []domain.SourceType{domain.SourceNewspaper},
		Fields: []FieldDef{
			{Key: "decedent", Label: "Decedent Name", Required: true},
			{Key: "title", Label: "Obituary Title", HelpText: "Headline if different from name"},
			{Key: "newspaper", Label: "Newspaper Name", Required: true},
			{Key: "location", Label: "Place of Publication"},
			{Key: "date", Label: "Publication Date", Required: true},
			{Key: "page", Label: "Page"},
		},
		FullFormat:  `{{with .Field "title"}}"{{.}}" (obituary), {{end}}{{.Field "newspaper"}}{{with .Field "location"}} ({{.}}){{end}}, {{.Field "date"}}{{with .Field "page"}}, p. {{.}}{{end}}; obituary for {{.Field "decedent"}}.`,
		ShortFormat: `{{.Field "newspaper"}}, {{.Field "date"}}, obituary for {{.Field "decedent"}}.`,
	},

	// ── Published Works ─────────────────────────────────────────────

	{
		ID:          "published.book",
		Name:        "Book (Authored)",
		Category:    "Published Works",
		Description: "Book with a single author or co-authors.",
		SourceTypes: []domain.SourceType{domain.SourceBook},
		Fields: []FieldDef{
			{Key: "author", Label: "Author", Required: true},
			{Key: "title", Label: "Title", Required: true},
			{Key: "publisher_loc", Label: "Place of Publication"},
			{Key: "publisher", Label: "Publisher"},
			{Key: "year", Label: "Year of Publication"},
			{Key: "page", Label: "Page(s)"},
		},
		FullFormat:  `{{.Field "author"}}, {{.Field "title"}}{{with .Field "publisher_loc"}} ({{.}}{{with $.Field "publisher"}}: {{.}}{{end}}{{with $.Field "year"}}, {{.}}{{end}}){{end}}{{with .Field "page"}}, {{.}}{{end}}.`,
		ShortFormat: `{{.Field "author"}}, {{.Field "title"}}{{with .Field "page"}}, {{.}}{{end}}.`,
	},
	{
		ID:          "published.compiled",
		Name:        "Book (Compiled/Edited)",
		Category:    "Published Works",
		Description: "Compiled or edited volume.",
		SourceTypes: []domain.SourceType{domain.SourceBook},
		Fields: []FieldDef{
			{Key: "editor", Label: "Editor/Compiler", Required: true},
			{Key: "role", Label: "Role", HelpText: "e.g. editor, compiler"},
			{Key: "title", Label: "Title", Required: true},
			{Key: "publisher_loc", Label: "Place of Publication"},
			{Key: "publisher", Label: "Publisher"},
			{Key: "year", Label: "Year of Publication"},
			{Key: "page", Label: "Page(s)"},
		},
		FullFormat:  `{{.Field "editor"}}{{with .Field "role"}}, {{.}}{{end}}, {{.Field "title"}}{{with .Field "publisher_loc"}} ({{.}}{{with $.Field "publisher"}}: {{.}}{{end}}{{with $.Field "year"}}, {{.}}{{end}}){{end}}{{with .Field "page"}}, {{.}}{{end}}.`,
		ShortFormat: `{{.Field "editor"}}, {{.Field "title"}}{{with .Field "page"}}, {{.}}{{end}}.`,
	},
	{
		ID:          "published.journal",
		Name:        "Journal/Periodical Article",
		Category:    "Published Works",
		Description: "Article in a scholarly journal or periodical.",
		SourceTypes: []domain.SourceType{domain.SourceBook},
		Fields: []FieldDef{
			{Key: "author", Label: "Author", Required: true},
			{Key: "article_title", Label: "Article Title", Required: true},
			{Key: "journal", Label: "Journal Name", Required: true},
			{Key: "volume", Label: "Volume"},
			{Key: "issue", Label: "Issue/Number"},
			{Key: "date", Label: "Date", HelpText: "Publication date or season+year"},
			{Key: "pages", Label: "Page(s)"},
		},
		FullFormat:  `{{.Field "author"}}, "{{.Field "article_title"}}," {{.Field "journal"}}{{with .Field "volume"}} {{.}}{{end}}{{with .Field "issue"}} ({{.}}){{end}}{{with .Field "date"}} [{{.}}]{{end}}{{with .Field "pages"}}: {{.}}{{end}}.`,
		ShortFormat: `{{.Field "author"}}, "{{.Field "article_title"}}," {{.Field "journal"}}{{with .Field "pages"}}: {{.}}{{end}}.`,
	},
	{
		ID:          "published.database_online",
		Name:        "Online Database",
		Category:    "Published Works",
		Description: "Searchable database published online (e.g. Ancestry, FamilySearch).",
		SourceTypes: []domain.SourceType{domain.SourceWebpage},
		Fields: []FieldDef{
			{Key: "database_title", Label: "Database Title", Required: true},
			{Key: "website", Label: "Website Name", Required: true},
			{Key: "url", Label: "URL"},
			{Key: "entry_for", Label: "Entry For", HelpText: "Person or record cited", Required: true},
			{Key: "accessed", Label: "Date Accessed", HelpText: "Date you viewed the record"},
			{Key: "citing", Label: "Citing", HelpText: "Original source the database cites"},
		},
		FullFormat:  `"{{.Field "database_title"}}," {{.Field "website"}}{{with .Field "url"}} ({{.}}{{with $.Field "accessed"}} : accessed {{.}}{{end}}){{end}}, entry for {{.Field "entry_for"}}{{with .Field "citing"}}; citing {{.}}{{end}}.`,
		ShortFormat: `"{{.Field "database_title"}}," {{.Field "website"}}, entry for {{.Field "entry_for"}}.`,
	},

	// ── Manuscripts & Archives ──────────────────────────────────────

	{
		ID:          "archive.document",
		Name:        "Archive/Manuscript Document",
		Category:    "Manuscripts & Archives",
		Description: "Unpublished document in an archive or manuscript collection.",
		SourceTypes: []domain.SourceType{domain.SourceArchive},
		Fields: []FieldDef{
			{Key: "document_title", Label: "Document Title/Description", Required: true},
			{Key: "date", Label: "Document Date"},
			{Key: "collection", Label: "Collection Name"},
			{Key: "series", Label: "Series"},
			{Key: "box", Label: "Box"},
			{Key: "folder", Label: "Folder"},
			{Key: "repository", Label: "Repository/Archive", Required: true},
			{Key: "location", Label: "Repository Location", HelpText: "City and state/country"},
		},
		FullFormat:  `{{.Field "document_title"}}{{with .Field "date"}}, {{.}}{{end}}{{with .Field "collection"}}; {{.}}{{end}}{{with .Field "series"}}, {{.}}{{end}}{{with .Field "box"}}, box {{.}}{{end}}{{with .Field "folder"}}, folder {{.}}{{end}}; {{.Field "repository"}}{{with .Field "location"}}, {{.}}{{end}}.`,
		ShortFormat: `{{.Field "document_title"}}{{with .Field "date"}} ({{.}}){{end}}, {{.Field "repository"}}.`,
	},
	{
		ID:          "archive.court",
		Name:        "Court Record",
		Category:    "Manuscripts & Archives",
		Description: "Probate, civil, or criminal court records.",
		SourceTypes: []domain.SourceType{domain.SourceArchive},
		Fields: []FieldDef{
			{Key: "jurisdiction", Label: "Court/Jurisdiction", HelpText: "e.g. County Probate Court", Required: true},
			{Key: "location", Label: "Location", HelpText: "County and state", Required: true},
			{Key: "record_type", Label: "Record Type", HelpText: "e.g. Will, Probate Packet, Case File", Required: true},
			{Key: "case_name", Label: "Case/Estate Name", Required: true},
			{Key: "date", Label: "Date"},
			{Key: "book_page", Label: "Book/Page"},
			{Key: "case_num", Label: "Case/File Number"},
		},
		FullFormat:  `{{.Field "jurisdiction"}}, {{.Field "location"}}, {{.Field "record_type"}}, {{.Field "case_name"}}{{with .Field "date"}}, {{.}}{{end}}{{with .Field "book_page"}}; {{.}}{{end}}{{with .Field "case_num"}}; case/file no. {{.}}{{end}}.`,
		ShortFormat: `{{.Field "jurisdiction"}}, {{.Field "location"}}, {{.Field "record_type"}}, {{.Field "case_name"}}.`,
	},
	{
		ID:          "archive.land",
		Name:        "Land/Property Record",
		Category:    "Manuscripts & Archives",
		Description: "Deeds, land grants, surveys, and property records.",
		SourceTypes: []domain.SourceType{domain.SourceArchive},
		Fields: []FieldDef{
			{Key: "jurisdiction", Label: "Recording Office", HelpText: "e.g. County Recorder", Required: true},
			{Key: "location", Label: "Location", Required: true},
			{Key: "record_type", Label: "Record Type", HelpText: "e.g. Deed, Land Grant", Required: true},
			{Key: "grantor", Label: "Grantor"},
			{Key: "grantee", Label: "Grantee"},
			{Key: "date", Label: "Date"},
			{Key: "book_page", Label: "Book/Page", Required: true},
		},
		FullFormat:  `{{.Field "jurisdiction"}}, {{.Field "location"}}, {{.Field "record_type"}}{{with .Field "grantor"}}; {{.}}{{end}}{{with .Field "grantee"}} to {{.}}{{end}}{{with .Field "date"}}, {{.}}{{end}}; {{.Field "book_page"}}.`,
		ShortFormat: `{{.Field "jurisdiction"}}, {{.Field "location"}}, {{.Field "record_type"}}, {{.Field "book_page"}}.`,
	},

	// ── Digital & Web ───────────────────────────────────────────────

	{
		ID:          "digital.website",
		Name:        "Website/Webpage",
		Category:    "Digital & Web",
		Description: "General website or webpage.",
		SourceTypes: []domain.SourceType{domain.SourceWebpage},
		Fields: []FieldDef{
			{Key: "author", Label: "Author/Creator"},
			{Key: "page_title", Label: "Page Title", Required: true},
			{Key: "website", Label: "Website Name", Required: true},
			{Key: "url", Label: "URL", Required: true},
			{Key: "accessed", Label: "Date Accessed"},
		},
		FullFormat:  `{{with .Field "author"}}{{.}}, {{end}}"{{.Field "page_title"}}," {{.Field "website"}} ({{.Field "url"}}{{with .Field "accessed"}} : accessed {{.}}{{end}}).`,
		ShortFormat: `"{{.Field "page_title"}}," {{.Field "website"}}.`,
	},
	{
		ID:          "digital.database_image",
		Name:        "Digital Image of Original Record",
		Category:    "Digital & Web",
		Description: "Digital image of an original record viewed online.",
		SourceTypes: []domain.SourceType{domain.SourceWebpage},
		Fields: []FieldDef{
			{Key: "record_description", Label: "Record Description", HelpText: "What the original record is", Required: true},
			{Key: "website", Label: "Website Name", Required: true},
			{Key: "url", Label: "URL"},
			{Key: "accessed", Label: "Date Accessed"},
			{Key: "original_source", Label: "Original Source", HelpText: "Citation for the original record", Required: true},
		},
		FullFormat:  `{{.Field "record_description"}}, digital image, {{.Field "website"}}{{with .Field "url"}} ({{.}}{{with $.Field "accessed"}} : accessed {{.}}{{end}}){{end}}; citing {{.Field "original_source"}}.`,
		ShortFormat: `{{.Field "record_description"}}, {{.Field "website"}}.`,
	},
	{
		ID:          "digital.online_db_entry",
		Name:        "Online Database Entry",
		Category:    "Digital & Web",
		Description: "Individual entry in an online database or index.",
		SourceTypes: []domain.SourceType{domain.SourceWebpage},
		Fields: []FieldDef{
			{Key: "database_title", Label: "Database Title", Required: true},
			{Key: "website", Label: "Website Name", Required: true},
			{Key: "url", Label: "URL"},
			{Key: "entry_for", Label: "Entry For", Required: true},
			{Key: "accessed", Label: "Date Accessed"},
		},
		FullFormat:  `"{{.Field "database_title"}}," {{.Field "website"}}{{with .Field "url"}} ({{.}}{{with $.Field "accessed"}} : accessed {{.}}{{end}}){{end}}, entry for {{.Field "entry_for"}}.`,
		ShortFormat: `"{{.Field "database_title"}}," {{.Field "website"}}, entry for {{.Field "entry_for"}}.`,
	},

	// ── Personal Knowledge ──────────────────────────────────────────

	{
		ID:          "personal.interview",
		Name:        "Interview/Oral History",
		Category:    "Personal Knowledge",
		Description: "Personal interview, oral history, or conversation.",
		SourceTypes: []domain.SourceType{domain.SourceInterview},
		Fields: []FieldDef{
			{Key: "interviewee", Label: "Interviewee", Required: true},
			{Key: "relationship", Label: "Relationship", HelpText: "Relationship to subject or researcher"},
			{Key: "location", Label: "Interview Location"},
			{Key: "date", Label: "Date of Interview", Required: true},
			{Key: "interviewer", Label: "Interviewer"},
			{Key: "format", Label: "Format", HelpText: "e.g. in person, telephone, video call"},
		},
		FullFormat:  `{{.Field "interviewee"}}{{with .Field "relationship"}} ({{.}}){{end}}, interview by {{with .Field "interviewer"}}{{.}}{{else}}author{{end}}{{with .Field "date"}}, {{.}}{{end}}{{with .Field "location"}}; {{.}}{{end}}{{with .Field "format"}}; {{.}}{{end}}.`,
		ShortFormat: `{{.Field "interviewee"}}, interview{{with .Field "date"}}, {{.}}{{end}}.`,
	},
	{
		ID:          "personal.correspondence",
		Name:        "Correspondence/Letter",
		Category:    "Personal Knowledge",
		Description: "Personal letter, email, or written correspondence.",
		SourceTypes: []domain.SourceType{domain.SourceCorrespond},
		Fields: []FieldDef{
			{Key: "author", Label: "Author/Sender", Required: true},
			{Key: "recipient", Label: "Recipient", Required: true},
			{Key: "date", Label: "Date", Required: true},
			{Key: "subject", Label: "Subject/Re"},
			{Key: "format", Label: "Format", HelpText: "e.g. letter, email, text message"},
			{Key: "held_by", Label: "Held By", HelpText: "Who possesses the original"},
		},
		FullFormat:  `{{.Field "author"}} to {{.Field "recipient"}}{{with .Field "subject"}}, "{{.}}"{{end}}, {{.Field "date"}}{{with .Field "format"}}; {{.}}{{end}}{{with .Field "held_by"}}; privately held by {{.}}{{end}}.`,
		ShortFormat: `{{.Field "author"}} to {{.Field "recipient"}}, {{.Field "date"}}.`,
	},
}
